exclude:
  dirs:
  - .git
  - .hg
  - .bzr
  - .svn
  - .idea
  - .vscode
  - .vs
  - venv
  - env
  - .venv
  - .env
  - node_modules
  - __pycache__
  - dist
  - build
  - target
  - coverage
  - vendor
  - bower_components
  - .cache
  - .sass-cache
  - .ipynb_checkpoints
  - tmp
  - temp
  files:
  - project_summary.md
  - .project2md.yml
  - '**/__*.md'
  - .git/**
  - .gitignore
  - .gitmodules
  - .gitattributes
  - .hg/**
  - .hgignore
  - .bzr/**
  - .bzrignore
  - .svn/**
  - '**/dist/**'
  - '**/build/**'
  - '**/target/**'
  - '**/coverage/**'
  - '**/__pycache__/**'
  - '**/*.pyc'
  - '**/*.pyo'
  - '**/*.pyd'
  - '**/node_modules/**'
  - '**/.idea/**'
  - '**/.vscode/**'
  - '**/.vs/**'
  - '**/*.sublime-workspace'
  - '**/*.sublime-project'
  - '**/.DS_Store'
  - '**/desktop.ini'
  - '**/Thumbs.db'
  - '**/ehthumbs.db'
  - '**/*.tmp'
  - '**/*.temp'
  - '**/*.swp'
  - '**/*~'
  - '**/*.bak'
  - '**/*.old'
  - '**/*.orig'
  - '**/.ipynb_checkpoints/**'
  - '**/.cache/**'
  - '**/.sass-cache/**'
  - '**/logs/**'
  - '**/*.log'
  - '**/npm-debug.log'
  - '**/yarn-debug.log'
  - '**/yarn-error.log'
  - '**/*.exe'
  - '**/*.dll'
  - '**/*.so'
  - '**/*.dylib'
  - '**/*.obj'
  - '**/*.o'
  - '**/*.a'
  - '**/*.lib'
  - '**/*.bin'
  - '**/*.class'
  - '**/*.mo'
  - '**/*.zip'
  - '**/*.tar.gz'
  - '**/*.7z'
  - '**/*.rar'
  - '**/*.gz'
  - '**/*.bz2'
  - '**/*.xz'
  - '**/*.lzma'
  - '**/*.zst'
  - '**/*.lz4'
  - '**/*.jpg'
  - '**/*.jpeg'
  - '**/*.png'
  - '**/*.gif'
  - '**/*.bmp'
  - '**/*.ico'
  - '**/*.mp4'
  - '**/*.mov'
  - '**/*.avi'
  - '**/*.flv'
  - '**/*.mkv'
  - '**/*.wmv'
  - '**/*.mp3'
  - '**/*.wav'
  - '**/*.ogg'
  - '**/*.flac'
  - '**/*.aac'
  - '**/*.wma'
  - '**/*.pdf'
  - '**/*.doc'
  - '**/*.docx'
  - '**/*.xls'
  - '**/*.xlsx'
  - '**/*.ppt'
  - '**/*.pptx'
  - '**/*.odt'
  - '**/*.ods'
  - '**/*.odp'
  - '**/*.rtf'
  - '**/*.db'
  - '**/*.sqlite'
  - '**/*.sql'
  - '**/*.dbf'
  - '**/*.mdb'
  - '**/*.accdb'
  - '**/*.shp'
general:
  collapse_empty_dirs: true
  max_depth: 10
  max_file_size: 1MB
  stats_in_output: true
include:
  dirs: []
  files:
  - '**/*.md'
  - '**/*.py'
  - '**/*.js'
  - '**/*.ts'
  - '**/*.java'
  - '**/*.c'
  - '**/*.cpp'
  - '**/*.h'
output:
  format: markdown
  stats: true
